[package]
name = "emver"
version = "0.1.0"
authors = ["Keagan McClelland <keagan.mcclelland@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.6.1"
nom = "5.1.2"
serde = { version = "1.0.117", optional = true }
fp-core = "0.1.9"
