[package]
name = "emver"
version = "0.1.0"
authors = ["Keagan McClelland <keagan@start9labs.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
description = "Semver extension with optional 4th digit given patch semantics. Designed for package distributors"
keywords = ["version", "semver", "embassy", "wasm"]
documentation = "https://docs.rs/emver"
repository = "https://github.com/Start9Labs/emver-rs"


[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
either = "1.6.1"
nom = "5.1.2"
serde = { version = "1.0.117", optional = true }
wasm-bindgen = { version = "0.2.68", optional = true }
fp-core = "0.1.9"

[dev-dependencies]
proptest = "0.10.1"
